language: node_js
sudo: required

osx_image: xcode8.3
dist: precise

node_js:
  - "6"


#env:
#  - CXX=gcc-4.8
#  - CC=gcc-4.8

os:
  - linux
  - osx


before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update; sudo apt-get install build-essential -y; fi
  - node --version
  - npm --version
  - openssl version
  - python --version
  - ssh -V
  - pip -V

script:
  - npm install
  - python build.py


addons:
  ssh_known_hosts: web.sourceforge.net


after_success:
  - openssl aes-256-cbc -K $encrypted_906d16ae5679_key -iv $encrypted_906d16ae5679_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - chmod 600 /tmp/deploy_rsa
  - scp -i /tmp/deploy_rsa dist/AboutCode*.tar.gz aboutcode-rel@web.sourceforge.net:/home/frs/project/aboutcode-manager/builds/
