version: '{build}'

image: Visual Studio 2013

platform:
  - x64

install:
  - ps: Install-Product node 6 x64
  - node --version
  - npm --version
  - openssl version
  - python --version
  - ssh -V
  - pip -V

build_script:
  - npm install
  - python build.py

test: off
